# Dynamic configuration
# https://docs.traefik.io/reference/dynamic-configuration/file/

tls:
  options:
    default:
      minVersion: VersionTLS12
      # sniStrict: true # not work def cert
    mintls13:
      minVersion: VersionTLS13
      # sniStrict: true # not work def cert
  stores:
    default:
      defaultCertificate:
        certFile: "/certificates/traefik_default.crt"
        keyFile: "/certificates/traefik_default.key"
  certificates:
    - certFile: "/certificates/traefik_default.crt"
      keyFile: "/certificates/traefik_default.key"
      stores:
        - default
    - certFile: "/certificates/traefik_hello.eirc.mos.ru.crt"
      keyFile: "/certificates/traefik_hello.eirc.mos.ru.key"
      stores:
        - default
